name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron:  '0 6 * * SAT'

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
        components: rustfmt
    - run: cargo +stable fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
        components: clippy
    - run: cargo +stable clippy --all-targets -- -D warnings

  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - run: cargo +stable install cargo-audit
    - run: cargo +stable audit

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: nightly
    - run: cargo +nightly doc --all-features

  test:
    needs: [fmt, clippy, audit, doc]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
    - run: cargo +${{ matrix.rust }} test
    - run: cargo +${{ matrix.rust }} test --no-default-features --tests
    - run: cargo +${{ matrix.rust }} test --all-features

  sanitize:
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, leak]
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: nightly
    - run: RUSTFLAGS="-Z sanitizer=${{ matrix.sanitizer }}" cargo +nightly test --tests --lib --all-features --target x86_64-unknown-linux-gnu

  fuzz:
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, leak]
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: nightly
    - run: cargo +nightly install cargo-fuzz
    - run: cargo +nightly fuzz run -s ${{ matrix.sanitizer }} fuzzer -- -max_total_time=120

  coverage:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: nightly
    - run: cargo +nightly install cargo-tarpaulin
    - run: for i in 0 1 2 3 4 5 6 7 8 9; do cargo +nightly tarpaulin --all-features --out Xml && break; done
    - run: bash <(curl -s https://codecov.io/bash) -C $GITHUB_SHA -B ${GITHUB_REF#refs/heads/} -Z
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  benchmark:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - run: cargo +stable bench --all-features
